name: Run test on pull request

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  pull_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      #New step — install dependencies
      - name: Environment setup
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check if main.py exists
        run: |
          if [ -f main.py ]; then
            echo "✅ main.py found, running it..."
            python main.py
          else
            echo "❌ main.py not found, skipping execution."
            exit 1
          fi

      - name: Run tests
        run: python test.py
