name: Run Python Script

on: [push]

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Check if main.py exists
        run: |
#          if [ -f main.py ]; then
#            echo "✅ main.py found, running it..."
            python main.py
#          fi
