name: Auto Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ✅ fetch all history and tags

      #New step — install dependencies
      - name: Environment setup
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Fetch tags
        run: git fetch --tags

      # Get the latest tag and increment it automatically
      - name: Determine next version
        id: version
        run: |
          # Get latest tag (if any)
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $latest_tag"

          # Remove 'v' prefix and split into major.minor.patch
          version=${latest_tag#v}
          IFS='.' read -r major minor patch <<< "$version"

          # Increment patch version
          patch=$((patch + 1))
          new_tag="v${major}.${minor}.${patch}"

          echo "New version: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      # Create the new tag
      - name: Create new tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.version.outputs.new_tag }}
          git push origin ${{ steps.version.outputs.new_tag }}

      # Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.new_tag }}
          name: Release ${{ steps.version.outputs.new_tag }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
